### ISSUE TITLE
riss and coprocessor in g++ ?

### ISSUE THREAD

**Issue by malipivo** [tuzz/snake-egg-puzzle#1]
Hello, I'd like to write a feedback and about a point where I've got stuck.  Just in case, you have got some tips or hints for me. So this is not a real issue with your code.

Installing Ruby... OK.
Installing Sentient... OK.
Installing Lingeling... OK.
Running `pretty_print.rb`... OK.

But I cannot run `search_minimal.rb`. Installing `riss` and `coprocessor` is a problem.  It probably requires Objective C++, but I'm not able to pass it to the compiler.  From the `riss-427/Makefile` file it goes to the `riss-427/core/Makefile` and then back to the `riss-427/mtl/template.mk`.  The problem is with `friend Lit ...` in `riss-427/core/SolverTypes.h`. I've deleted that keyword `friend`.  But still, there is a problem with `inline Lit operator ~(Lit p)` etc.  I enclose the result of `make riss >vypis1.txt 2>&1`.
[vypis1.txt](https://github.com/tuzz/snake-egg-puzzle/files/5987105/vypis1.txt)
I'm working with gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04).

**Update 16. 2. 2021.**  I've found `https://github.com/conp-solutions/riss`, so I'll try this source code.  ---  And it works for me!  Hurayyy!

After `sentient --run snake-egg.json --machine lingeling --assign-file example/assignments.json | ruby search_minimal.rb` I'm getting:
```
Waiting for input...
Writing minimal.snt...
Compiling program...
Killed
Searching...
Iteration 1, testing {"grid":{"0":{"2":-1,"0":9},"2":{"0":-1}}}
Unexpected end of JSON input
Traceback (most recent call last):
	7: from search_minimal.rb:35:in `<main>'
	6: from search_minimal.rb:35:in `upto'
	5: from search_minimal.rb:38:in `block in <main>'
	4: from search_minimal.rb:38:in `each'
	3: from search_minimal.rb:38:in `combination'
	2: from search_minimal.rb:58:in `block (2 levels) in <main>'
	1: from /usr/lib/ruby/2.7.0/json/common.rb:156:in `parse'
/usr/lib/ruby/2.7.0/json/common.rb:156:in `parse': 783: unexpected token at '' (JSON::ParserError)
```
After this error, I've deleted `--optimize` in `search_minimal.rb` and this is what I'm getting:
```
$ sentient --run snake-egg.json --machine lingeling --assign-file example/assignments.json | ruby search_minimal.rb 
Waiting for input...
Writing minimal.snt...
Compiling program...
Searching...
Iteration 1, testing {"grid":{"0":{"2":-1,"0":9},"2":{"0":-1}}}
Iteration 2, testing {"grid":{"0":{"2":-1,"1":9},"2":{"0":-1}}}
[...]
```

To complete and in some way conclude my research, I made these steps:
-- I've downloaded riss via `git clone https://github.com/conp-solutions/riss`,
-- I've followed its README file, plus
-- I've run `make riss-core` and `make coprocessor` at the end,
-- I've copied `bin/riss-core` to the `/usr/local/bin` as `riss` and `bin/coprocessor` to that same destination directory.
-- I've deleted `--optimize` in the `search_minimal.rb`, I wasn't digging deeper in this matter what's wrong.
-- Then, I've run `sentient --run snake-egg.json --machine lingeling --assign-file example/assignments.json | ruby search_minimal.rb` and it runs as expected.

**Comment by tuzz** [comment]
Hey, sorry for the late follow up. Well done on getting it working!

I think what might have happened is that the Riss Coprocessor program's interface has changed between versions. The `--optimize` flag calls out to the coprocessor to try and minimize the problem before it starts the search for solutions.

I don't think it matters that it hasn't run the optimizer. I wouldn't have expected it to speed up the search much because `lingeling` already does a great job at optimizing the problem.
